WebAppBlog/Blog/Blog/Controllers/AuthorController.cs
using AutoMapper;
using System.Collections.Generic;
using BlogBL;
using System.Web.Mvc;
using Blog.Models;
using BlogBL.Models;
using System.Linq;

namespace Blog.Controllers
{
    public class AuthorController : Controller
    {

        private readonly IAuthorService _authorService;
        private readonly IMapper _mapper;
        public AuthorController(IAuthorService authorService, IMapper mapper)
        {
            _authorService = authorService;
            _mapper = mapper;
        }


        // GET: Author
        public ActionResult Index()
        {
            var listBL = _authorService.QueryAll();

            if (!listBL.Any())
            {
                return RedirectToAction("NoAuthors");
            }

            var authors = _mapper.Map<IEnumerable<AuthorModel>>(listBL);

            return View(authors);
        }

        // GET: Author/Details/5
        public ActionResult Details(int id)
        {
            var modelBL = _authorService.FindById(id);
            var author = _mapper.Map<AuthorModel>(modelBL);

            ViewBag.Articles = _authorService.GetArticleDictionaryIdTitle(id);

            return View(author);

        }

        // GET: Author/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Author/Create
        [HttpPost]
        public ActionResult Create(AuthorModel model)
        {



            //TODO: Add insert logic here
            if (string.IsNullOrEmpty(model.Avatar))
                model.Avatar = "~/Resources/user-blank.png";

            var modelBL = _mapper.Map<AuthorBL>(model);

            _authorService.Create(modelBL);

            return RedirectToAction("Index");
        }

        // GET: Author/Edit/5
        public ActionResult Edit(int id)
        {
            var modelBL = _authorService.FindById(id);
            var author = _mapper.Map<AuthorModel>(modelBL);

            return View(author);
        }

        // POST: Author/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, AuthorModel model)
        {
            // TODO: Add update logic here

            var modelBL = _mapper.Map<AuthorBL>(model);
            _authorService.Edit(modelBL);

            return RedirectToAction("Index");
        }

        // POST: Author/Delete/5
        //[HttpDelete]
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add delete logic here
                _authorService.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult NoAuthors()
        {
            return View();
        }

    }
}

WebAppBlog/Blog/Blog/Views/Author/Create.cshtml
@model Blog.Models.AuthorModel

@{
    ViewBag.Title = "Create";
}

<h2>Add new author</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <b class = "control-label col-md-2">First name</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b class="control-label col-md-2">Last name</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b class="control-label col-md-2">Nickname</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nickname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nickname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b class="control-label col-md-2">Avatar</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Avatar, new { htmlAttributes = new { @class = "form-control", placeholder = "Insert URL" } })
                @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })
                <!--<p>
            <div>
                <img id="user_img"
                     height="64"
                     width="64"
                     style="border:solid" />
            </div>
        <p>
            <div>
                <input type="file" title="search image" id="file" name="file" onchange="show(this)" />
            </div>-->
            </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

WebAppBlog/Blog/Blog/Views/Author/Details.cshtml
@model Blog.Models.AuthorModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AuthorModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            First name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            Last name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nickname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nickname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avatar)
        </dt>

        <dd>
            <img src="@Url.Content(Model.Avatar)" width="64" height="64" />
        </dd>

        <dt>
            <b>Published articles</b>
        </dt>
        @foreach (var item in ViewBag.Articles)
        {
            <dd>
                    @Html.ActionLink($"{@item.Value}", "Details", "Articles", new {id = item.Key}, null)
            </dd>
        }
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebAppBlog/Blog/Blog/Views/Author/Edit.cshtml
@model Blog.Models.AuthorModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AuthorModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <b class="control-label col-md-2">First Name</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b class="control-label col-md-2">Last Name</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b class="control-label col-md-2">Nickname</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nickname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nickname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b class="control-label col-md-2">Avatar</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Avatar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAppBlog/Blog/Blog/Views/Author/Index.cshtml
@model IEnumerable<Blog.Models.AuthorModel>

<p>
    @Html.ActionLink("Add new author", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Nickname
        </th>
        <th>
            Avatar
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nickname)
            </td>
            <td>
                <img src="@Url.Content(item.Avatar)" width="32" height="32" class="img-circle" />
            </td>
            <td>
                @Html.ActionLink("Edit info", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                <button type="button" class="btn btn-info" data-toggle="modal" data-nick="@item.Nickname" data-id="@item.Id" data-target="#deleteModal">Delete</button>
            </td>
        </tr>
    }

</table>

<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Delete author</h4>
            </div>
            <center>
                <div class="modal-body">
                </div>
            </center>
            <div class="modal-footer">
                <button type="button" id="confirm" class="btn btn-primary">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).on('show.bs.modal', '#deleteModal', function (event) {
            var btn = $(event.relatedTarget)
            var nick = btn.data('nick')
            var id = btn.data('id')
            var modal = $(event.currentTarget)
            modal.find('.modal-body').text('Are you sure you want to delete ' + nick + '? All published articles will also be deleted.')
            href = '@Url.Action("Delete", "Author")?id=' + id
            modal.find('.modal-footer button[id=confirm]').attr('onclick', 'location.href=\'' + href + '\'')
        })
    </script>
    }

WebAppBlog/Blog/Blog/Views/Author/NoAuthors.cshtml
<h2>Currently there are no authors :(</h2>

<p>
    @Html.ActionLink("Fill your data and become one!", "Create")
</p>